#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sandbox")]
	public partial class FMSBudgetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FMSBudgetDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SandboxConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FMSBudgetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FMSBudgetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FMSBudgetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FMSBudgetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BudgetExport> BudgetExports
		{
			get
			{
				return this.GetTable<BudgetExport>();
			}
		}
		
		public System.Data.Linq.Table<vwFMSBudget> vwFMSBudgets
		{
			get
			{
				return this.GetTable<vwFMSBudget>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="FMSBudget.BudgetExport")]
	public partial class BudgetExport
	{
		
		private string _Doc;
		
		private System.Nullable<int> _Year;
		
		private string _Period;
		
		private System.Nullable<int> _Program;
		
		private string _ProgramDesc;
		
		private System.Nullable<int> _Type;
		
		private string _TypeDesc;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<decimal> _AmtRounded;
		
		public BudgetExport()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc", DbType="VarChar(24)")]
		public string Doc
		{
			get
			{
				return this._Doc;
			}
			set
			{
				if ((this._Doc != value))
				{
					this._Doc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="VarChar(12)")]
		public string Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this._Period = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Program", DbType="Int")]
		public System.Nullable<int> Program
		{
			get
			{
				return this._Program;
			}
			set
			{
				if ((this._Program != value))
				{
					this._Program = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramDesc", DbType="VarChar(50)")]
		public string ProgramDesc
		{
			get
			{
				return this._ProgramDesc;
			}
			set
			{
				if ((this._ProgramDesc != value))
				{
					this._ProgramDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeDesc", DbType="VarChar(50)")]
		public string TypeDesc
		{
			get
			{
				return this._TypeDesc;
			}
			set
			{
				if ((this._TypeDesc != value))
				{
					this._TypeDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmtRounded", DbType="Money")]
		public System.Nullable<decimal> AmtRounded
		{
			get
			{
				return this._AmtRounded;
			}
			set
			{
				if ((this._AmtRounded != value))
				{
					this._AmtRounded = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwFMSBudget")]
	public partial class vwFMSBudget
	{
		
		private string _ProgramDesc;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<decimal> _Budget;
		
		private System.Nullable<decimal> _BudgetUtilized;
		
		public vwFMSBudget()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramDesc", DbType="VarChar(50)")]
		public string ProgramDesc
		{
			get
			{
				return this._ProgramDesc;
			}
			set
			{
				if ((this._ProgramDesc != value))
				{
					this._ProgramDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Budget", DbType="Money")]
		public System.Nullable<decimal> Budget
		{
			get
			{
				return this._Budget;
			}
			set
			{
				if ((this._Budget != value))
				{
					this._Budget = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetUtilized", DbType="Decimal(22,6)")]
		public System.Nullable<decimal> BudgetUtilized
		{
			get
			{
				return this._BudgetUtilized;
			}
			set
			{
				if ((this._BudgetUtilized != value))
				{
					this._BudgetUtilized = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
